name: fade_animation_delayed
description: "FadeAnimationDelayed is a custom Flutter widget that allows you to display content with a delay and various animations."
version: 0.0.2
homepage: "https://github.com/SwanFlutter/fade_animation_delayed"
repository: "https://github.com/SwanFlutter/fade_animation_delayed"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


